Add deployment instructions for PowerStore
dell/osp-integration pull request #3
Opened 2020-12-25 09:39 UTC by ivanpch

2020-12-29 07:51 UTC, vlad-belogrudov approved these changes

2021-01-03 20:37 UTC, gaelrehault approved these changes

2021-01-05 21:27 UTC, arkadykanevsky requested changes
small editorial changes needed

2021-01-05 21:27 UTC, arkadykanevsky commented on osp-deploy/cinder/README.md
> +Afterwards, open the copy (~/templates/cinder-dellemc-powerstore-config.yaml) and edit it as you see fit. The following shows a sample content of the file. The files will list optional params that th
override -> overwrite

2021-01-05 21:27 UTC, arkadykanevsky commented on osp-deploy/cinder/README.md
> +# Cinder Dell EMC PowerMax backend, configured via puppet.
PowerMax -> Powerstore

2021-01-05 21:27 UTC, arkadykanevsky commented on osp-deploy/cinder/README.md
> +# To configure multiple PowerStore backends, use CinderPowerStoreMultiConfig to
example above already covers two powerstores.

#To configure multiple PowerStore backends, use CinderPowerStoreMultiConfig to
# assign parameter values specific to that backend. For example:
->
#To configure multiple PowerStore backends differently, use CinderPowerStoreMultiConfig to
# assign parameter values specific to each backend. For example:

2021-01-06 20:29 UTC, arkadykanevsky commented on osp-deploy/cinder/README.md
> +# To configure multiple PowerStore backends, use CinderPowerStoreMultiConfig to
Ivan, can you make these small changes so we can merge the patch?

2021-01-06 20:36 UTC, arkadykanevsky approved these changes

2021-01-06 20:37 UTC, merged